name: Scheduled Data Download

permissions:
  contents: write

on:
  schedule:
    - cron: '10 17 * * *'

  workflow_dispatch:

jobs:
  download-data:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Debug env vars
        run: env | grep 'USER\|PASS'

      - name: Run data download script
        run: python data_download.py

      - name: Commit and push changes
        run: |
          git config --global user.email "falaknaazkhxn@gmail.com"
          git config --global user.name "falaknaazkhan14"
          git add data/downloaded_data.csv
          git commit -m "Update data - $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push
