name: Scheduled Data Download

on:
  schedule:
    # Runs every day at 6 AM UTC
    - cron: '10 17 * * *'

  workflow_dispatch:  # Allows you to manually trigger the workflow from GitHub

jobs:
  download-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas  # Add any libraries your script needs

      - name: Run data download script
        run: python download_data.py

    
